
import { GoogleGenAI, Type } from "@google/genai";
import { PosterContent } from "./types";

/**
 * Generates marketing content and brand identity from a product image using Gemini 3 Flash.
 */
export const generatePosterContent = async (
  base64Image: string,
  brandName?: string,
  customSlogan?: string,
  context?: string,
  contactInfo?: { phone?: string; email?: string; website?: string }
): Promise<PosterContent> => {
  // Always use process.env.API_KEY directly when initializing the GoogleGenAI client instance
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `You are a professional creative director. 
  Look at the attached product image and generate marketing slogans and brand identity.
  
  USER INPUTS:
  - Brand/Product Name: ${brandName || "Generate a creative one if not obvious"}
  - Preferred Slogan: ${customSlogan || "Generate one if empty"}
  - Context/Idea: ${context || "Use your best creative judgment based on the image"}

  INSTRUCTIONS:
  1. Use the provided Brand Name if available.
  2. Use the provided Slogan if available.
  3. generate a 'background_word' which is one single powerful word related to the product (e.g., 'FRESH', 'GLOW', 'PURE', 'DRIVE').
  4. generate a short 'cta_text' like 'SHOP NOW', 'ORDER NOW', or a price point.
  
  Return valid JSON with:
  1. brand_name (string)
  2. short_slogan (max 8 words)
  3. long_slogan (max 15 words)
  4. cta_text (string)
  5. background_word (string)
  6. emotional_tone (one of: bold, premium, playful, minimal, energetic)
  7. product_category (single word description)`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.0-flash',
    contents: {
      parts: [
        { inlineData: { data: base64Image, mimeType: 'image/png' } },
        { text: prompt }
      ]
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          brand_name: { type: Type.STRING },
          short_slogan: { type: Type.STRING },
          long_slogan: { type: Type.STRING },
          cta_text: { type: Type.STRING },
          background_word: { type: Type.STRING },
          emotional_tone: {
            type: Type.STRING,
            enum: ['bold', 'premium', 'playful', 'minimal', 'energetic']
          },
          product_category: { type: Type.STRING }
        },
        required: ["brand_name", "short_slogan", "long_slogan", "cta_text", "background_word", "emotional_tone", "product_category"]
      }
    }
  });

  const text = response.text || '{}';
  const content = JSON.parse(text) as PosterContent;
  content.company_info = contactInfo || {};
  return content;
};

/**
 * Enhances the product image by generating a new background while keeping the product central.
 * Uses gemini-2.0-flash-exp with image generation capabilities.
 */
export const enhanceProductImage = async (
  base64Image: string,
  tone: string,
  userVisualDescription: string,
  context?: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const visualDirectives = `
    TASK: Generate a stunning commercial poster image featuring the product from the attached image.
    
    ENVIRONMENT: ${userVisualDescription || 'A clean, premium commercial studio setup with dramatic lighting.'}
    MOOD: ${tone || 'premium'}
    ${context ? `CONTEXT: ${context}` : ''}

    CRITICAL REQUIREMENTS:
    1. PRODUCT HERO: The product from the source image should be the absolute center of attention.
    2. BACKGROUND: Create a beautiful, high-end professional commercial background that matches the environment description.
    3. LIGHTING: Use cinematic commercial lighting with rim lights, soft shadows, and depth.
    4. NO TEXT: Do not add any text, logos, or watermarks to the image.
    5. COMPOSITION: Keep the top 30% and bottom 20% relatively clean for text overlays.
    6. STYLE: Make it look like a professional advertising campaign photo.
    
    Generate a single high-quality image.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash-exp',
      contents: {
        parts: [
          { inlineData: { data: base64Image, mimeType: 'image/png' } },
          { text: visualDirectives }
        ]
      },
      config: {
        responseModalities: ['Text', 'Image']
      }
    });

    // Check for image in response parts
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        const mimeType = part.inlineData.mimeType || 'image/png';
        return `data:${mimeType};base64,${part.inlineData.data}`;
      }
    }

    // If no image generated, fall back to using the original image
    console.warn("No image generated by AI, using original image");
    return `data:image/png;base64,${base64Image}`;
  } catch (error: any) {
    console.error("Image generation error:", error);
    // Fall back to original image on error
    return `data:image/png;base64,${base64Image}`;
  }
};
